# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField()),
                ('crate_time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('executor', models.CharField(max_length=10)),
                ('projects', models.CharField(max_length=50)),
                ('test_result', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_env_id', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('ip', models.CharField(max_length=20, null=True)),
                ('port', models.CharField(max_length=40, null=True)),
                ('username', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=32, null=True)),
                ('switch', models.CharField(max_length=10, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('sender', models.CharField(max_length=20, null=True)),
                ('receiver', models.CharField(max_length=100, null=True)),
                ('cc', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('ip', models.CharField(max_length=20, null=True)),
                ('port', models.CharField(max_length=40, null=True)),
                ('checked', models.CharField(max_length=10, null=True)),
                ('project_id', models.CharField(max_length=100, null=True)),
                ('data_base_id', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('result_type', models.CharField(max_length=10)),
                ('headers', models.CharField(max_length=100)),
                ('request', models.CharField(max_length=100, null=True)),
                ('response', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('desc', models.CharField(max_length=40, null=True)),
                ('interface_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tcheckdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sql', models.CharField(max_length=100)),
                ('expectation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tdatavar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('var_name', models.CharField(max_length=10)),
                ('sql', models.CharField(max_length=10)),
                ('custom_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('interface_name', models.CharField(max_length=20)),
                ('case_number', models.IntegerField()),
                ('case_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tpreoperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=10)),
                ('case_name', models.CharField(max_length=20)),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Trequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.CharField(max_length=20)),
                ('request_value', models.CharField(max_length=20)),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Tresponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_key', models.CharField(max_length=20)),
                ('response_value', models.CharField(max_length=20)),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Testcase')),
            ],
        ),
        migrations.AddField(
            model_name='tdatavar',
            name='basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Testcase'),
        ),
        migrations.AddField(
            model_name='tcheckdb',
            name='basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Testcase'),
        ),
    ]
