# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20170928_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('project_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('switch', models.BooleanField()),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('sender', models.CharField(max_length=20, null=True)),
                ('receiver', models.CharField(max_length=100, null=True)),
                ('cc', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('context', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='email_setting',
        ),
        migrations.RemoveField(
            model_name='project',
            name='test',
        ),
    ]
